name: Docker Deploy CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker context create remote-docker --docker host=ssh://root@descenty.ru;
          docker context use remote-docker
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
      - run: echo TOKEN=${{ secrets.TOKEN }} >> .env
      - run: docker compose up
