name: Docker Deploy CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker context create remote-docker --docker host=ssh://root@descenty.ru;
          docker context use remote-docker
      - uses: actions/checkout@v4
      - name: Add SSH key
        run: echo ${{ secrets.KEY }} > /home/runner/.ssh/id_rsa
      - run: echo TOKEN=${{ secrets.TOKEN }} >> .env
      - run: docker compose up
